### ISSUE TITLE
I have no issue. I just want to contact you.

### ISSUE THREAD

**Issue by theoneandonlyshadow** [Goekdeniz-Guelmez/Goekdeniz-Guelmez#1]
I couldnt see any other way to contact you so i created an issue here. I have a doubt regarding your JARVIS Model by dolphin-llama3 LLM. Please [contact me here](https://madhavdotjs.netlify.app/public/contact.html) so we can discuss the issue. Thank you.

**Comment by Goekdeniz-Guelmez** [comment]
No problem, I've send you an email.
